/*****************************************************************************
 * Program Description: OOP assignment 2025. 
 *  Building a Java application of a maching learning classifier based on the naive bayes classifier. 
 * Date: 26/03/25
 * Author: Renee Low
 * 
 *                           !!!!!! NOTE !!!!!!!
 * The dataset that was used in this assignment was generated by ChatGPT. 
 ****************************************************************************/

public class Control {
    public static void main(String[] args) {
        GUI gui = new GUI("Predictor-inator");
    }
}