import java.util.ArrayList;

/*****************************************************************************
 * Program Description: OOP assignment 2025. 
 *  Building a Java application of a maching learning classifier based on the naive bayes classifier. 
 * Date: 26/03/25
 * Author: Renee Low
 * 
 *                           !!!!!! NOTE !!!!!!!
 * The dataset that was used in this assignment was generated by ChatGPT. 
 ****************************************************************************/

public class Control {
    public static void main(String[] args) {
        FileProcessor fileManager = new FileProcessor("device_status_dataset.csv");
        // connecting to file
        fileManager.connectFile();
        fileManager.getFileWriter();

        // writing to file
        fileManager.writeLineToFile("On,Strong,Active,Running,No");
        fileManager.closeWriteFile();

        // printing out the results
        ArrayList<String> lines = fileManager.readFile();
        for (String line : lines) {
            System.out.println(line);
        }
        
    }
}